site_name: formBuilder
site_url: http://formbuilder.online
repo_url: https://github.com/kevinchappell/formBuilder.git
repo_name: 'GitHub'
site_description: A jQuery plugin for drag and drop form creation
site_favicon: favicon.ico
theme: readthedocs
pages:
- Introduction: index.md
- Getting Started: getting-started.md
- Development:
    - Overview: development.md
    - Icon Font: editing-fonts.md
- Demos:
  - Basic: demos/basic.md
  - Toggle formBuilder: demos/toggle-builder.md
  - Translating: demos/translation.md
- Options:
    - Overview: options.md
    - append/prepend: options/appendPrepend.md
    - controlPosition: options/controlPosition.md
    - controlOrder: options/controlOrder.md
    - disableFields: options/disableFields.md
    - fieldRemoveWarn: options/fieldRemoveWarn.md
    - messages: options/messages.md
    - notify: options/notify.md
    - sortableControls: options/sortableControls.md
- Contributing: contributing.md
- About:
  - License: license.md
extra_css:
  - 'css/site.css'
extra_javascript:
- 'js/scripts.js'
